export const activityActionTypes = {
    GET_ACTIVITIES_START : 'GET_ACTIVITIES_START',
    GET_ACTIVITIES_SUCCESS : 'GET_ACTIVITIES_SUCCESS',
    GET_ACTIVITIES_FAILURE : 'GET_ACTIVITIES_FAILURE',

    GET_ACTIVITIY_START : 'GET_ACTIVITIY_START',
    GET_ACTIVITIY_SUCCESS : 'GET_ACTIVITIY_SUCCESS',
    GET_ACTIVITIY_FAILURE : 'GET_ACTIVITIY_FAILURE',
    
    SELECT_ACTIVITY: 'SELECT_ACTIVITY',
    
    CREATE_ACTIVITY_START: 'CREATE_ACTIVITY_START', 
    CREATE_ACTIVITY_SUCCESS: 'CREATE_ACTIVITY_SUCCESS', 
    CREATE_ACTIVITY_FAILURE: 'CREATE_ACTIVITY_FAILURE', 
    CREATE_ACTIVITY_MENU_BUTTON_CLICK: 'CREATE_ACTIVITY_MENU_BUTTON_CLICK', 

    EDIT_ACTIVITY_START: 'EDIT_ACTIVITY_START', 
    EDIT_ACTIVITY_SUCCESS: 'EDIT_ACTIVITY_SUCCESS', 
    EDIT_ACTIVITY_FAILURE: 'EDIT_ACTIVITY_FAILURE', 

    DELETE_ACTIVITY_START: 'DELETE_ACTIVITY_START', 
    DELETE_ACTIVITY_SUCCESS: 'DELETE_ACTIVITY_SUCCESS', 
    DELETE_ACTIVITY_FAILURE: 'DELETE_ACTIVITY_FAILURE', 
}